services:
    - type: web
      name: ChatUltraEdition
      runtime: static
      buildCommand: echo done
      staticPublishPath: dist
      routes:
        - type: rewrite
          source: /*
          destination: /index.html
  